source "http://rubygems.org"

gem "rack", "~> 1.2"
gem "tilt", "~> 1.3"
gem "i18n", "~> 0.5"
gem "sass", "~> 3.1"
gem "compass", "~> 0.11"
gem "activesupport", ">= 3.0"
gem 'sprockets', '~> 2.0.0.beta.14'